sudo: false
language: java
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2/repository"
script:
- clean install deploy --settings settings.xml
- clean install deploy -Pdev --settings settings.xml
env:
  global:
  - secure: ixdQyXS+BS31GZsBG/Qf0YO18hhRcgfDLPASwxsfvd6hroGPS5rWtA+lMpORNxobnMm/w0bE2HGNEk3cCvF9P12XHLQDoN4wFZdnMwQM0a2rCSfpcm4cRO06A/yMl8MHLx0qkVF70jixj2opkcuSSSqhn+ZGRwHtzGgPdyblt+gUqPDk091dj7mwUxjpVTTyMeRRlIu2E1vuivjZ30jmMRXKDqPEAb3qil16P0smSgo1U7M0Vt0j/iPFY5MVeqgOE2ZhpzNZ7b6tlTQE/ERIFeVbrvPvhT0hfK2MQdyc6EVs3H53JCZpax/VyaqzTH7Jy45NAicN+YSP6pd0cmrqfrXKwi5G3sn55ibRrZzcKCKs2KQY0ZuaTf4W2vaepIa7/zjXTQF803eHvvpTbXfqukwVCgNw/uP6J7oKtgQMKUErX3YF40gZRwK7NYRMGKK4UnO7R2JkEM/DlHK0qRDvwnuRlou5Tj2amCk6C6QTgU0GTp2bUzPgapb1jaM6wcNrPtPfzPcoxaDtQ7OgJzrfn+W0DohmcDiWjWgJaXibYCJMxqLwXB/j0bWmrpV3hyxke/VWp+BmaYKMqxtrXAIFwZAuRsCdsAX/ZsztIlIdAWzIXWM0LybAmT0tOKgbTjAkdtbvyLhAdiEfVzXIjkryQDkJvHrei6Vc82GFaVxolzw=
  - secure: fch9ic9sR2hYehaOybBCBzZ5wRXiejhjKUKy95usxtEd++x8+jgvzTTAOab7sHHNl1rHYfJrLZZl9+c6xvSUiPZMHJHq2J7FxXjgPR97qxOGwKAPKHn6EeNSS2b/AXNHM15Q6aGUOzkrNlB3HgME2gTNl0kcQDVjjexP0AjbSYRw8HRczMgGX+ZPRW8IK3lDFD1fcMgJ1jIETDszca6L5GgYs1poV3iEviZYROQuE3Gxvbi9VCSqUdogeLME6pMH3hR/NKP4KVY7QWRGgzRSjn0nof+PgB/VuihgR2fO3HB2c94P9f3Zw7tXQUpOVy0QdAOXHkDNu5ljhMYBNjS5g5J5epK9L5XdGzlB02t6xvbaqykZrn2yRIA34wjDLDdsw7ath/g1PgUWTpomSgoiJGOsGzGFBAbiCya2EGrq73qReAgNo5McSFlHpDz7Fgw+iRxCUX+N7JRcB5pDlEbmPCXHio7saeAKO8TqtglgORuJ180PICsklQylif7L8iQmXtOdUKdJVWNWBKgxX0+V14BJZvDB9t5fkfIoI1P4ieMjBA8WADMzlpt6Ybr2s1jblSEtPqYUOpQpftxfZnkxQqjuLV50OqeueXdI+Sl2HSnkAa05LSbzzb1XTnAx55c4sZnSY9xLT4G0dmHcsYT75eFTCPgy8NkUSNmkKZkWQzs=
